{
  organization(login: "MYDEVVKR") {
    name
    teams(first: 100) {
      edges {
        node {
          name
          parentTeam {
            name
          }
          members(first: 100) {
            totalCount
            edges {
              role
              node {
                login
              }
            }
          }
        }
      }
    }
  }
}
