# This is a basic workflow to help you get started with Actions

name: Fetch Github Team for organization

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Fetch all github teams for organization MYDEVVKR
        env: # Or as an environment variable
          my_token: ${{ secrets.MYDEVVKR_PAT }}
        run: |
          chmod +x github_admin.sh
          ./github_admin.sh

      - name: Upload the user report as a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: Teams
          path: inactive_user.csv

      - name: Upload the User List with SAML Identity as Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: User List With Email
          path: user_list_with_email.csv
